name: heroes
version: 0
author: Vladimir Semyonov <tempname011@gmail.com>
category: Game

dependencies:
  - QuickCheck
  - base
  - bimap
  - binary
  - bytestring
  - containers
  - data-fix
  - data-default-class
  - generic-lens
  - generic-deriving
  - hashable
  - hashtables
  - lens
  - linear
  - mtl # XXX remove
  - primitive
  - safe
  - split
  - template-haskell
  - transformers
  - vector
  - field-optics

default-extensions:
  - DataKinds
  - DeriveFunctor
  - DeriveGeneric
  - DuplicateRecordFields
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies

ghc-options:
  - -Wall
  - -Werror

library:
  source-dirs:
    - src

tests:
  boxes:
    main: Main.hs
    dependencies:
      - heroes
      - QuickCheck
      - test-framework
      - test-framework-quickcheck2
