name: heroes-web
version: 0
author: Vladimir Semyonov <tempname011@gmail.com>
category: Game

dependencies:
  - heroes
  #
  - base
  - bytestring
  - containers
  - generic-lens
  - ghcjs-base
  - hashable
  - vector

default-extensions:
  - DataKinds
  - DeriveFunctor
  - DeriveGeneric
  - DuplicateRecordFields
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies

ghc-options:
  - -Wall
  - -Werror

library:
  source-dirs:
    - src
  js-sources: jsbits/*.js

executables:
  game:
    source-dirs: misc
    main: Main.hs
    ghc-options:
      - -DGHCJS_BROWSER
      - -DGHCJS_LOG_BUFFER
      - -DGHCJS_SCHED_QUANTUM=1
      - -DGHCJS_SCHED_CHECK=256
      - -DGHCJS_BUSY_YIELD=1
      - -DGHCJS_GC_INTERVAL=60000
    cpp-options: -DMAIN_MODULE=Web.Artifacts.Game
    dependencies:
      - heroes-web
