name: heroes-native
version: 0
author: Vladimir Semyonov <tempname011@gmail.com>
category: Game

dependencies:
  - heroes
  #
  - JuicyPixels
  - base
  - bytestring
  - containers
  - data-default-class
  - directory
  - ekg
  - ekg-json
  - generic-lens
  - ghc-prim
  - gl
  - sdl2
  - sdl2-mixer
  - split
  - vector

default-extensions:
  - DataKinds
  - DeriveFunctor
  - DeriveGeneric
  - DuplicateRecordFields
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies

ghc-options:
  - -Wall
  - -Werror

library:
  source-dirs:
    - src

executables:
  game:
    source-dirs: misc
    main: Main.hs
    cpp-options: -DMAIN_MODULE=Native.Artifacts.Game
    ghc-options:
      - -threaded
      - -with-rtsopts=-N
      - -with-rtsopts=-T # for EKG
    dependencies:
      - heroes-native

  compile-essentials:
    source-dirs: misc
    main: Main.hs
    cpp-options: -DMAIN_MODULE=Native.Artifacts.CompileEssentials
    dependencies:
      - heroes-native

  compile-cursors:
    source-dirs: misc
    main: Main.hs
    cpp-options: -DMAIN_MODULE=Native.Artifacts.CompileCursors
    dependencies:
      - heroes-native
